name: flexiedit_tmp
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.9.18
  - pip=23.3
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - accelerate==0.16.0
      - diffusers==0.10.0
      - einops==0.7.0
      - fire==0.5.0
      - gradio==3.20.1
      - imageio==2.32.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - numpy==1.26.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - pillow==9.4.0
      - python-box==7.2.0
      - pyyaml==6.0.1
      - pytorch-lightning==2.2.1
      - rich==13.7.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - tokenizers==0.13.3
      - torchmetrics==1.3.1
      - tqdm==4.65.0
      - transformers==4.26.1
      - nltk==3.8.1
      - huggingface-hub==0.25.2 # revised 24.10.21